### ISSUE TITLE
Bei mehreren Datenreihen der gleichen Tabelle werden nur die Daten der letzten Datenreihe für alle Datenreihen gespeichert.

### ISSUE THREAD

**Issue by danielhoegel** [internHHC/python-backend#1]
Bei mehreren Mails etc. wird zwar die richtige Anzahl an Mails gespeichert, jedoch wird jede Mail mit den Daten der Mail gespeichert, die als letztes kommt.

input:
![image](https://cloud.githubusercontent.com/assets/18073247/22721013/9c214014-edae-11e6-8935-e85309ed5765.png)

output:
![image](https://cloud.githubusercontent.com/assets/18073247/22721025/a684b4be-edae-11e6-8ef8-9262eaa302b5.png)

EDIT:
Der Fehler tritt nur bei einem updateContact, nicht bei einem createContact auf.

**Comment by AxXxel001** [comment]
Ich weiß wo der Fehler liegt. In der update query wird beim WHERE nur "contact_id=" eingesetzt. Das ist natürlich nicht richtig weil dann immer alle Mails für einen contact überschrieben werden. Am Ende haben dann alle den Wert der letzten Email. Man muss hier mit en IDs der Mails arbeiten (genauso phone, etc.). Kann es sein, dass die echten IDs auch beim selecten gar nicht zurück gegeben werden?

**Comment by danielhoegel** [comment]
Ja richtig, die stehen auch gar nicht in den TABLE_COLUNMS.
